# Generated by Django 6.1 on 2026-09-23 21:15

import dj_craft_tally.identifiers
import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def add_initial_units(apps, schema_editor):
    unit = apps.get_model("craft_tally", "Unit")
    unit.objects.bulk_create(
        [
            unit(code="item", name="Item", symbol="item", dimension="count"),
            unit(code="g", name="Gram", symbol="g", dimension="mass"),
            unit(
                code="kg",
                name="Kilogram",
                symbol="kg",
                dimension="mass",
                scale_to_base=Decimal("1000"),
            ),
            unit(code="mL", name="Millilitre", symbol="mL", dimension="volume"),
            unit(
                code="L",
                name="Litre",
                symbol="L",
                dimension="volume",
                scale_to_base=Decimal("1000"),
            ),
            unit(code="mm", name="Millimetre", symbol="mm", dimension="length"),
            unit(
                code="cm",
                name="Centimetre",
                symbol="cm",
                dimension="length",
                scale_to_base=Decimal("10"),
            ),
            unit(
                code="m",
                name="Metre",
                symbol="m",
                dimension="length",
                scale_to_base=Decimal("1000"),
            ),
            unit(code="mm2", name="Square millimetre", symbol="mm²", dimension="area"),
            unit(
                code="cm2",
                name="Square centimetre",
                symbol="cm²",
                dimension="area",
                scale_to_base=Decimal("100"),
            ),
            unit(
                code="m2",
                name="Square metre",
                symbol="m²",
                dimension="area",
                scale_to_base=Decimal("1000000"),
            ),
            unit(code="s", name="Second", symbol="s", dimension="time"),
            unit(
                code="min",
                name="Minute",
                symbol="min",
                dimension="time",
                scale_to_base=Decimal("60"),
            ),
            unit(
                code="h",
                name="Hour",
                symbol="h",
                dimension="time",
                scale_to_base=Decimal("3600"),
            ),
        ]
    )


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=dj_craft_tally.identifiers.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="A stable identifier, such as g, mL, or item.",
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("symbol", models.CharField(max_length=16)),
                (
                    "dimension",
                    models.CharField(
                        choices=[
                            ("count", "Count"),
                            ("mass", "Mass"),
                            ("volume", "Volume"),
                            ("length", "Length"),
                            ("area", "Area"),
                            ("time", "Time"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "scale_to_base",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("1"),
                        help_text="How many base units this unit represents within its dimension.",
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.000001")),
                            django.core.validators.MaxValueValidator(
                                Decimal("999999999.999999")
                            ),
                        ],
                    ),
                ),
            ],
            options={
                "ordering": ("dimension", "scale_to_base", "name"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("dimension", "symbol"),
                        name="unique_unit_dimension_symbol",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("scale_to_base__lte", Decimal("999999999.999999"))
                        ),
                        name="unit_scale_to_base_within_range",
                    ),
                ],
            },
        ),
        migrations.RunPython(add_initial_units, migrations.RunPython.noop),
    ]
