# Generated by Django 6.1 on 2026-09-23 21:18

import dj_craft_tally.identifiers
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("craft_tally", "0002_workshop"),
    ]

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=dj_craft_tally.identifiers.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="materials",
                        to="craft_tally.unit",
                    ),
                ),
                (
                    "workshop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="materials",
                        to="craft_tally.workshop",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="MaterialLot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=dj_craft_tally.identifiers.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=200)),
                ("supplier", models.CharField(blank=True, max_length=200)),
                ("package_count", models.PositiveIntegerField(default=1)),
                (
                    "quantity_per_package",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.000001"))
                        ],
                    ),
                ),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lots",
                        to="craft_tally.material",
                    ),
                ),
            ],
            options={
                "ordering": ("material__name", "reference"),
            },
        ),
        migrations.AddConstraint(
            model_name="material",
            constraint=models.UniqueConstraint(
                fields=("workshop", "name"), name="unique_workshop_material_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="materiallot",
            constraint=models.UniqueConstraint(
                fields=("material", "reference"), name="unique_material_lot_reference"
            ),
        ),
    ]
