# Generated by Django 6.1 on 2026-09-23 21:20

import dj_craft_tally.identifiers
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("craft_tally", "0004_equipment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blueprint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=dj_craft_tally.identifiers.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("output_name", models.CharField(max_length=200)),
                (
                    "output_quantity",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("1"),
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "output_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="blueprint_outputs",
                        to="craft_tally.unit",
                    ),
                ),
                (
                    "workshop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="blueprints",
                        to="craft_tally.workshop",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="BlueprintMaterialRequirement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=dj_craft_tally.identifiers.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.000001"))
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "blueprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements",
                        to="craft_tally.blueprint",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="blueprint_requirements",
                        to="craft_tally.material",
                    ),
                ),
            ],
            options={
                "ordering": ("blueprint__name", "material__name"),
            },
        ),
        migrations.AddConstraint(
            model_name="blueprint",
            constraint=models.UniqueConstraint(
                fields=("workshop", "name"), name="unique_workshop_blueprint_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="blueprintmaterialrequirement",
            constraint=models.UniqueConstraint(
                fields=("blueprint", "material"),
                name="unique_blueprint_material_requirement",
            ),
        ),
    ]
