# Generated by Django 6.1 on 2026-09-23 21:27

import dj_craft_tally.identifiers
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("craft_tally", "0005_blueprint"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=dj_craft_tally.identifiers.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("active", "Active"),
                            ("stalled", "Stalled"),
                            ("complete", "Complete"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="planned",
                        max_length=16,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "blueprint",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projects",
                        to="craft_tally.blueprint",
                    ),
                ),
                (
                    "workshop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projects",
                        to="craft_tally.workshop",
                    ),
                ),
            ],
            options={
                "ordering": ("status", "name"),
            },
        ),
        migrations.CreateModel(
            name="ProjectStatusChange",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=dj_craft_tally.identifiers.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "previous_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("planned", "Planned"),
                            ("active", "Active"),
                            ("stalled", "Stalled"),
                            ("complete", "Complete"),
                            ("abandoned", "Abandoned"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("active", "Active"),
                            ("stalled", "Stalled"),
                            ("complete", "Complete"),
                            ("abandoned", "Abandoned"),
                        ],
                        max_length=16,
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                (
                    "recorded_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_changes",
                        to="craft_tally.project",
                    ),
                ),
            ],
            options={
                "ordering": ("occurred_at", "recorded_at"),
                "indexes": [
                    models.Index(
                        fields=["project", "occurred_at"],
                        name="craft_tally_project_7cd41d_idx",
                    )
                ],
            },
        ),
    ]
