# Generated by Django 6.1 on 2026-09-23 21:28

import dj_craft_tally.identifiers
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("craft_tally", "0006_project_status_history"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=dj_craft_tally.identifiers.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sequence",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("reference", models.CharField(blank=True, max_length=200, unique=True)),
                ("source_reference", models.CharField(blank=True, max_length=500)),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("success", "Success"),
                            ("failure", "Failure"),
                            ("partial_success", "Partial success"),
                        ],
                        max_length=20,
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                (
                    "recorded_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "blueprint",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project_steps",
                        to="craft_tally.blueprint",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project_steps",
                        to="craft_tally.equipment",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="steps",
                        to="craft_tally.project",
                    ),
                ),
            ],
            options={
                "ordering": ("project", "sequence"),
            },
        ),
        migrations.CreateModel(
            name="ProjectStepMeasurement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=dj_craft_tally.identifiers.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "project_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measurements",
                        to="craft_tally.projectstep",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project_step_measurements",
                        to="craft_tally.unit",
                    ),
                ),
            ],
            options={
                "ordering": ("project_step__sequence", "name"),
            },
        ),
        migrations.AddConstraint(
            model_name="projectstep",
            constraint=models.UniqueConstraint(
                fields=("project", "sequence"), name="unique_project_step_sequence"
            ),
        ),
        migrations.AddConstraint(
            model_name="projectstepmeasurement",
            constraint=models.UniqueConstraint(
                fields=("project_step", "name"), name="unique_project_step_measurement"
            ),
        ),
    ]
