# Generated by Django 6.1 on 2026-09-23 21:29

import dj_craft_tally.identifiers
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("craft_tally", "0007_project_steps"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=dj_craft_tally.identifiers.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("receive", "Received"),
                            ("produce", "Produced"),
                            ("consume", "Consumed"),
                            ("adjust", "Adjusted"),
                        ],
                        max_length=16,
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                (
                    "recorded_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_transactions",
                        to="craft_tally.project",
                    ),
                ),
                (
                    "project_step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_transactions",
                        to="craft_tally.projectstep",
                    ),
                ),
                (
                    "workshop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_transactions",
                        to="craft_tally.workshop",
                    ),
                ),
            ],
            options={
                "ordering": ("-occurred_at", "-recorded_at"),
            },
        ),
        migrations.CreateModel(
            name="InventoryTransactionLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=dj_craft_tally.identifiers.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=6, max_digits=15)),
                ("notes", models.TextField(blank=True)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_lines",
                        to="craft_tally.material",
                    ),
                ),
                (
                    "material_lot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_lines",
                        to="craft_tally.materiallot",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="craft_tally.inventorytransaction",
                    ),
                ),
            ],
            options={
                "ordering": ("transaction__occurred_at", "id"),
            },
        ),
        migrations.AddIndex(
            model_name="inventorytransaction",
            index=models.Index(
                fields=["occurred_at"], name="craft_tally_occurred_at_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventorytransaction",
            index=models.Index(fields=["kind"], name="craft_tally_kind_c17cd4_idx"),
        ),
        migrations.AddConstraint(
            model_name="inventorytransactionline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity", 0), _negated=True),
                name="inventory_transaction_line_quantity_nonzero",
            ),
        ),
    ]
